In [38]:
import numpy as np
import pandas as pd

In [39]:
df = pd.read_csv("dataset/iris.csv")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [41]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [42]:
df.shape

(150, 5)

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X = df.drop(columns=['species'])
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [45]:
Y = df[['species']]
Y

species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [46]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,train_size=0.8)

In [47]:
X_train.shape

(120, 4)

In [48]:
X_test.shape

(30, 4)

In [49]:
Y_train.shape

(120, 1)

In [50]:
Y_test.shape

(30, 1)

In [51]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [63]:
a = le.fit_transform(Y_train)

In [64]:
a

array([0, 0, 1, 2, 1, 0, 1, 0, 2, 0, 2, 0, 2, 0, 1, 0, 1, 0, 2, 0, 2, 1,
       1, 2, 0, 0, 0, 2, 0, 2, 2, 1, 2, 2, 2, 1, 0, 1, 1, 2, 0, 2, 0, 2,
       0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 1, 2, 2, 0, 1, 2, 1, 0,
       2, 1, 0, 2, 2, 2, 1, 1, 2, 2, 0, 0, 0, 2, 0, 1, 0, 2, 2, 0, 1, 0,
       0, 2, 0, 1, 0, 0, 1, 2, 0, 2, 2, 1, 0, 2, 2, 1, 1, 2, 1, 1, 1, 0,
       0, 2, 0, 0, 1, 0, 2, 1, 1, 0])

In [65]:
b = le.fit_transform(Y_test)

In [66]:
b

array([2, 1, 2, 1, 1, 2, 2, 1, 1, 0, 2, 2, 0, 2, 2, 0, 1, 1, 0, 0, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 0])

In [67]:
from sklearn.linear_model import LinearRegression


In [68]:
lr = LinearRegression()

In [69]:
lr.fit(X_train,a)

LinearRegression()

In [70]:
lr.predict(X_test)

array([ 1.9562113 ,  0.9432831 ,  2.26540338,  1.39438843,  1.26073058,
        1.79660538,  1.85580597,  1.25726638,  1.2246028 , -0.06605039,
        2.04413011,  2.12933204,  0.11854016,  1.93443618,  2.00389248,
        0.07074408,  1.1366889 ,  1.41500305, -0.08063063, -0.08026416,
        1.82763511,  1.20895715,  1.0173837 ,  0.98245532,  1.19510985,
        1.58329371,  1.07946734,  1.36246269,  1.31755657,  0.02382984])

In [72]:
lr.score(X_train,a)

0.9331001589041301

In [75]:
lr.score(X_test,b)

0.9034327740725164