# NUMPY LIBRARY

In [1]:
import numpy as np
np.__version__

'1.21.5'

# CREATE A 1-D ARRAY USING array()

In [4]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(a.dtype)
print(a.shape)

[1 2 3]
int32
(3,)


# CREATE A 1-D ARRAY USING arange()

In [3]:
import numpy as np
a=np.arange(3)
print(a)
print(a.dtype)
print(a.shape)

[0 1 2]
int32
(3,)


# CREATE A 2-D ARRAY USING array()

In [5]:
import numpy as np
b=np.array(([1,2,3],[4,5,6]))
print(b)
print(a.dtype)
print(a.shape)

[[1 2 3]
 [4 5 6]]
int32
(3,)


# CREATE A 2-D ARRAY USING arange()

In [8]:
import numpy as np
b=np.arange(10).reshape(2,5) #if we multiply numbers in reshape() it must become 10
print(b)
print(b.dtype)
print(b.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32
(2, 5)


In [9]:
import numpy as np
b=np.arange(10).reshape(5,2)
print(b)
print(b.dtype)
print(b.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
int32
(5, 2)


# CREATE A 3-D ARRAY USING array()

In [12]:
import numpy as np
c=np.array(
    [
    [[1,2,3],[5,6,7]],         #3 2-d array with 2-rows and 3-columns
    [[8,9,10],[11,12,13]],
    [[14,15,16],[17,18,19]]
    ]
)
print(c)
print(c.dtype)
print(c.shape)

[[[ 1  2  3]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]

 [[14 15 16]
  [17 18 19]]]
int32
(3, 2, 3)


# CREATE A 3-D ARRAY USING arange()

In [18]:
import numpy as np
c=np.arange(1,19).reshape(3,3,2)  #3 2-d array with 3-rows and 2-columns
print(c)                          
print(a.dtype)
print(a.shape)      #shape() gives total number of elements in array

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
int32
(3,)


# CREATE ARRAY OF ONES (1-D)

In [25]:
import numpy as np
d=np.ones(2,dtype=np.int32) #dtype of numpy is default float64
print(d)
print(d.dtype)
print(d.shape)

[1 1]
int32
(2,)


# CREATE ARRAY OF ONES(2-D)

In [27]:
import numpy as np
d=np.ones((2,3),dtype=np.int32)
print(d)
print(d.dtype)
print(d.shape)

[[1 1 1]
 [1 1 1]]
int32
(2, 3)


# CREATE ARRAY OF ONES(3-D)

In [30]:
import numpy as np
d=np.ones((3,2,3),dtype="int32")
print(d)
print(d.dtype)
print(d.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
int32
(3, 2, 3)


# CREATE ARRAY OF ZEROS(1-D)

In [31]:
import numpy as np
f=np.zeros((3),dtype=np.int32)
print(f)
print(f.dtype)
print(f.shape)

[0 0 0]
int32
(3,)


# CREATE ARRAY OF ZEROS(2-D)

In [33]:
import numpy as np
f=np.zeros((2,3),dtype=np.int32)
print(f)
print(f.dtype)
print(f.shape)

[[0 0 0]
 [0 0 0]]
int32
(2, 3)


# CREATE ARRAY OF ZEROS(3-D)

In [36]:
import numpy as np
f=np.zeros((3,2,3),dtype=np.int32)
print(f)
print(f.dtype)
print(f.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
int32
(3, 2, 3)


# CREATE AN ARRAY WITH RANDOM NUMBERS(1-D)

In [38]:
import numpy as np
a=np.random.randint(1,6,size=(6))
print(a)
print(a.dtype)
print(a.shape)

[2 2 3 5 2 2]
int32
(6,)


# CREATE AN ARRAY WITH RANDOM NUMBERS(2-D)

In [39]:
import numpy as np
b=np.random.randint(1,11,size=(2,3))  #size==shape
print(b)
print(b.dtype)
print(b.shape)

[[10  9  3]
 [ 2  3  8]]
int32
(2, 3)


# CREATE AN ARRAY WITH RANDOM NUMBERS(3-D)

In [41]:
import numpy as np
c=np.random.randint(10,21,size=(3,2,3))
print(c)
print(c.dtype)
print(c.shape)

[[[15 17 17]
  [12 19 10]]

 [[14 19 16]
  [18 18 19]]

 [[19 12 12]
  [12 19 16]]]
int32
(3, 2, 3)


# CREATE ARRAY WITH SINGLE LOW MULTIPLE HIGH

In [43]:
import numpy as np
a=np.random.randint(5,[10,20,30])
print(a)
print(a.dtype)
print(a.shape)

[ 6  8 24]
int32
(3,)


# CREATE ARRAY WITH MULTIPLE LOW SINGLE HIGH

In [51]:
import numpy as np
b=np.random.randint([1,2,3],10)
print(b)
print(b.dtype)
print(b.shape)

[2 2 6]
int32
(3,)


# CREATE ARRAY WITH MULTIPLE LOW MULTIPLE HIGH

In [2]:
import numpy as np
a=np.random.randint([1,2,3],[10,20,30])
print(a)
print(a.dtype)
print(a.shape)

[ 3  2 27]
int32
(3,)


# CREATE ARRAY WITH RANDOM NUMBERS USING randn() (1-D)

In [5]:
import numpy as np
a=np.random.randn(3)
print(a)
print(a.dtype)
print(a.shape)

[-1.08269211 -1.27965982 -1.19004382]
float64
(3,)


# CREATE NUMPY WITH RANDOM NUMBERS USING randn() (2-D)

In [8]:
import numpy as np
b=np.random.randn(3,2)
print(b)
print(b.dtype)
print(b.shape)

[[-0.23353583  0.02653656]
 [ 0.14683944 -0.22120399]
 [-0.18268175 -0.13126485]]
float64
(3, 2)


# CREATE ARRAY WITH RANDOM NUMBERS USING randn() (3-D)

In [10]:
import numpy as np
c=np.random.randn(3,3,2)
print(c)
print(c.dtype)
print(c.shape)

[[[ 0.17690788  1.5283026 ]
  [-0.51405264  0.08818944]
  [-0.60759473  0.01136548]]

 [[ 1.27045933  0.26684523]
  [ 0.7982055   0.69655462]
  [ 2.33320887  0.24936803]]

 [[ 0.1194499  -1.94728094]
  [ 1.84010729 -0.40432439]
  [ 0.25344769 -0.49382074]]]
float64
(3, 3, 2)


# CREATE ARRAY OF RANDOM NUMBERS USING rand()

In [2]:
import numpy as np
a=np.random.rand(3)
print(a)
print(a.dtype)
print(a.shape)

[0.3052765  0.97305904 0.60890098]
float64
(3,)


# POSITIVE INDEXING IN ARRAY(left - right)

In [8]:
#array with 1-D
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[2])
print(arr[7])    #permanent method
arr[3]           #not permanent method

3
8


4

In [10]:
#array with 2-D
import numpy as np
arr=np.array([[1,2,3],[5,6,7]])
print(arr[0,2])
print(arr[1,1])

3
6


In [12]:
#array with 3-D
import numpy as np
arr=np.array(
    [
        [[1,2,3],[4,5,6]],
        [[10,20,30],[12,13,14]],
        [[100,200,300],[400,500,600]]    
    ]
            )
print(arr[0,1,1])
print(arr[2,1,0])

5
400


# NEGETIVE INDEXING IN ARRAY(right - left)

In [17]:
#array with 1-D
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-2])
print(arr[-1])
print(arr[-7])

6
7
1


In [18]:
#array with 2-D
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[-1,-2])

5


In [21]:
#arry with 3-D
import numpy as np
arr=np.array(
    [
        [[1,2,3],[5,6,7]],
        [[12,13,14],[11,10,49]]
    ]
            )
print(arr[-1,-1,-3])
print(arr[-2,-1,-3])

11
5


# MIXING OF (+ AND -)

In [26]:
import numpy as np
arr=np.array(
    [
        [[2,3,4],[5,6,7]],
        [[10,2,4],[6,7,29]],
        [[22,11,14],[23,45,44]]
    ]
)
print(arr[1,1,1])
print(arr[-2,-1,-2])
print(arr[2,-1,2])
print(arr[-1,1,-2])

7
7
44
45


# NUMPY  ARRAY SLICING

slice elements from index 1 to index 5 from following array:

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


slice elements from index 4 to the end of the array

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


slice elements from the beginning to index 4(not included)

In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


# NEGETIVE SLICING

slice from the index 3 from the end to index 1 from the end:

In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


return every other elemrnt from index 1 to index 5

In [16]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-1:-5:-2])

[7 5]


return every other element from the entire array

In [18]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


# SLICING 2-D ARRAYS

from the second element,slice elements from index 1 to index 4(not included)

In [13]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


from both arrays, return index 2:

In [19]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


from both arrays,slice index 1 to index 4(not included),
this will return 2-d array 

In [21]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]
