# PANDAS SERIES

Series is an 1D labeled array capable of holding data of any type(integer,float,python objects, etc).The axis labeled are collectivelly called as index

#syntax : pd.Series(data,index,dtype,copy)

In [2]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5])
print(ser1)
print()
ser2 = pd.Series(['a','b','c','d','e'])
print(ser2)

0    1
1    2
2    3
3    4
4    5
dtype: int64

0    a
1    b
2    c
3    d
4    e
dtype: object


In [3]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5] , dtype = np.float64)
print(ser1)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64


In [7]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5],index=["num1","num2","num3","num4","num5"])
print(ser1)

num1    1
num2    2
num3    3
num4    4
num5    5
dtype: int64


In [9]:
import numpy as np
import pandas as pd
i = pd.Index(["num1","num2","num3","num4","num5"])
ser1 = pd.Series([1,2,3,4,5],i)
print(ser1)

num1    1
num2    2
num3    3
num4    4
num5    5
dtype: int64


creating Series using dictionary method

In [10]:
import numpy as np
import pandas as pd
ser1 = pd.Series({"Rohit":40,"KL":23,"Virat":100,"Panth":12,"Chahal":2})
print(ser1)

Rohit      40
KL         23
Virat     100
Panth      12
Chahal      2
dtype: int64


#  PANDAS DATAFRAMES

DataFrames is the collection of multiple Series

* SYNTAX : pd.DataFrame(array , index ,columns)

In [4]:
import numpy as np
import pandas as pd
arr = np.arange(0,9).reshape(3,3)
print("Numpy Array")
print(arr)
print()
df = pd.DataFrame(arr , index=['a','b','c'], columns=['A','B','C'])
print("Numpy DataFrame")
print(df)

Numpy Array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Numpy DataFrame
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [21]:
#Here single array stores marks of one student in every subject
import numpy as np
import pandas as pd
arr = np.array([[90,89,50,100],[78,90,77,89],[99,89,79,60]])
print("Numpy Array")
print(arr)
print()
df = pd.DataFrame(arr , index=['shridhar','gururaj','harshad'] , columns=['osa','python','java','se'])
print("Pandas DataFrame to store the marks of students in every subject")
print("--------------------------------")
print(df)

Numpy Array
[[ 90  89  50 100]
 [ 78  90  77  89]
 [ 99  89  79  60]]

Pandas DataFrame to store the marks of students in every subject
--------------------------------
          osa  python  java   se
shridhar   90      89    50  100
gururaj    78      90    77   89
harshad    99      89    79   60


In [73]:
#Here single array stores marks of every students in one subject , it is possible when we are using dictionary method ,we can change this by using T method
import numpy as np
import pandas as pd
df = pd.DataFrame({"osa":[90,78,99,77],"python":[89,90,87,88],"java":[89,60,99,100],"se":[99,100,78,88]} ,index=["Nihal","Tanishk","Ravi","Arun"])
print(df) 

         osa  python  java   se
Nihal     90      89    89   99
Tanishk   78      90    60  100
Ravi      99      87    99   78
Arun      77      88   100   88


In [62]:
import pandas as pd
i = pd.Index(["a","b","c","d"])
#ser1 = pd.Series([1,2,3,2] ,index=i)
#ser2 = pd.Series([8,9,5,8] ,index=i)
#df = pd.DataFrame({"osa":ser1 , "java":ser2})
df = pd.DataFrame([[1,8],[2,7],[3,5],[7,4]] , index=i , columns=["osa" ,"java"])
print(df)

   osa  java
a    1     8
b    2     7
c    3     5
d    7     4


# CREATE DATAFRAME CONTAINIMG INFORMATION ABOUT CITIES

In [71]:
import numpy as np
import pandas as pd
i = pd.Index(["Karnataka","Maharastra","Gujarat"])
#pop = pd.Series([1.2,3.0,2.0] , i)
#cap = pd.Series(["Bengalure","Mumbai","Gandhinagar"] , i)
#df = pd.DataFrame({"population":pop,"capital":cap})
df = pd.Datadf = pd.DataFrame([["1.2","Bengalure"],["2.0","Mumbai"],["3.0","Gandhinagar"]] , index=["Karnataka","Maharastara","Gujarat"] , columns=["Population","Capital"])
#df = pd.DataFrame([["1.2","Bengalure"],["2.0","Mumbai"],["3.0","Gandhinagar"]] , index=["Karnataka","Maharastara","Gujarat"] , columns=["Population","Capital"]).T
print(df)
# Here 'T' is transpos of matrix which converts rows to columns and vice versa

            Population      Capital
Karnataka          1.2    Bengalure
Maharastara        2.0       Mumbai
Gujarat            3.0  Gandhinagar


Possibilities of creating DataFrame through multiple series

1. Normal Series method

2. Transpose method

3. Dictionary method (key = Hedding , values = Series)(Don't need to give name in series)
                                                      
4. 2-D array method

In [75]:
#1.NORMAL SERIES METHOD
import numpy as np
import pandas as ps
i = pd.Index(["Karnataka","Maharastra","Gujarat"])
ser1 = pd.Series([1.2,3.4,1.1] , i ,name="population")
ser2 = pd.Series(["Bengalure","Mumbai","Gandhinagar"] , i ,name="capital")
df = pd.DataFrame([ser1,ser2])
print(df)

            Karnataka Maharastra      Gujarat
population        1.2        3.4          1.1
capital     Bengalure     Mumbai  Gandhinagar


In [76]:
#2.TRANSPOSE  METHOD
import numpy as np
import pandas as ps
i = pd.Index(["Karnataka","Maharastra","Gujarat"])
ser1 = pd.Series([1.2,3.4,1.1] , i ,name="population")
ser2 = pd.Series(["Bengalure","Mumbai","Gandhinagar"] , i ,name="capital")
df = pd.DataFrame([ser1,ser2]).T
print(df)

           population      capital
Karnataka         1.2    Bengalure
Maharastra        3.4       Mumbai
Gujarat           1.1  Gandhinagar


In [89]:
#3.DICTIONARY  METHOD
import numpy as np
import pandas as ps
i = pd.Index(["Karnataka","Maharastra","Gujarat"])
ser1 = pd.Series([1.2,3.4,1.1] , i )
ser2 = pd.Series(["Bengalure","Mumbai","Gandhinagar"] , i)
df = pd.DataFrame({"population":ser1,"capital":ser2})
print(df)

            population      capital
Karnataka          1.2    Bengalure
Maharastra         3.4       Mumbai
Gujarat            1.1  Gandhinagar


In [80]:
#4.2-D METHOD
import numpy as np
import pandas as ps
#i = pd.Index(["Karnataka","Maharastra","Gujarat"])
df = pd.Datadf = pd.DataFrame([["1.2","Bengalure"],["2.0","Mumbai"],["3.0","Gandhinagar"]] , index=["Karnataka","Maharastara","Gujarat"] , columns=["Population","Capital"])
print(df)

            Population      Capital
Karnataka          1.2    Bengalure
Maharastara        2.0       Mumbai
Gujarat            3.0  Gandhinagar


# HOW TO ADD NEW DATA TO A SERIES

In [83]:
import numpy as np
import pandas as pd
pop = pd.Series([1.2,3.0,2.0] , i ,name="population")
print(pop.append(pd.Series({"TamilNadu":7.7})))

Karnataka     1.2
Maharastra    3.0
Gujarat       2.0
TamilNadu     7.7
dtype: float64


C:\Users\CS-L2-PC09\AppData\Local\Temp\ipykernel_9592\2737838292.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(pop.append(pd.Series({"TamilNadu":7.7})))


METHOD 1

In [85]:
import numpy as np
import pandas as pd
df = pd.Datadf = pd.DataFrame([["1.2","Bengalure"],["2.0","Mumbai"],["3.0","Gandhinagar"]] , index=["Karnataka","Maharastara","Gujarat"] , columns=["Population","Capital"])
print(df.append(pd.DataFrame([["5.5","chennai"],["12.5","hyderabad"]] , index=["Tamil nadu","Andrapradesh"] , columns=["Population","Capital"])))

             Population      Capital
Karnataka           1.2    Bengalure
Maharastara         2.0       Mumbai
Gujarat             3.0  Gandhinagar
Tamil nadu          5.5      chennai
Andrapradesh       12.5    hyderabad


C:\Users\CS-L2-PC09\AppData\Local\Temp\ipykernel_9592\664069513.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame([["5.5","chennai"],["12.5","hyderabad"]] , index=["Tamil nadu","Andrapradesh"] , columns=["Population","Capital"])))


METHOD 2

In [93]:
import numpy as np
import pandas as ps
i = pd.Index(["Karnataka","Maharastra","Gujarat"])
pop = pd.Series([1.2,3.4,1.1] , i )
cap = pd.Series(["Bengalure","Mumbai","Gandhinagar"] , i)
df = pd.DataFrame({"population":pop,"capital":cap})
print(df.append(pd.DataFrame({"population":pd.Series({"Tamilnadu":5.5,"Andrapradesh":7.6}),
                             "capital":pd.Series({"Tamilnadu":"channai","Andrapradesh":"hydrabad"})
                             }
                            )
               )
     )

              population      capital
Karnataka            1.2    Bengalure
Maharastra           3.4       Mumbai
Gujarat              1.1  Gandhinagar
Tamilnadu            5.5      channai
Andrapradesh         7.6     hydrabad


C:\Users\CS-L2-PC09\AppData\Local\Temp\ipykernel_9592\435301407.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame({"population":pd.Series({"Tamilnadu":5.5,"Andrapradesh":7.6}),


# CONCAT NEW COLUMN TO DATAFRAME