# PANDAS SERIES

Series is an 1D labeled array capable of holding data of any type(integer,float,python objects, etc).The axis labeled are collectivelly called as index

#syntax : pd.Series(data,index,dtype,copy)

In [2]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5])
print(ser1)
print()
ser2 = pd.Series(['a','b','c','d','e'])
print(ser2)

0    1
1    2
2    3
3    4
4    5
dtype: int64

0    a
1    b
2    c
3    d
4    e
dtype: object


In [3]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5] , dtype = np.float64)
print(ser1)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64


In [7]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5],index=["num1","num2","num3","num4","num5"])
print(ser1)

num1    1
num2    2
num3    3
num4    4
num5    5
dtype: int64


In [9]:
import numpy as np
import pandas as pd
i = pd.Index(["num1","num2","num3","num4","num5"])
ser1 = pd.Series([1,2,3,4,5],i)
print(ser1)

num1    1
num2    2
num3    3
num4    4
num5    5
dtype: int64


creating Series using dictionary method

In [10]:
import numpy as np
import pandas as pd
ser1 = pd.Series({"Rohit":40,"KL":23,"Virat":100,"Panth":12,"Chahal":2})
print(ser1)

Rohit      40
KL         23
Virat     100
Panth      12
Chahal      2
dtype: int64


#  PANDAS DATAFRAMES

DataFrames is the collection of multiple Series

* SYNTAX : pd.DataFrame(array , index ,columns)

In [4]:
import numpy as np
import pandas as pd
arr = np.arange(0,9).reshape(3,3)
print("Numpy Array")
print(arr)
print()
df = pd.DataFrame(arr , index=['a','b','c'], columns=['A','B','C'])
print("Numpy DataFrame")
print(df)

Numpy Array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Numpy DataFrame
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [21]:
#Here single array stores marks of one student in every subject
import numpy as np
import pandas as pd
arr = np.array([[90,89,50,100],[78,90,77,89],[99,89,79,60]])
print("Numpy Array")
print(arr)
print()
df = pd.DataFrame(arr , index=['shridhar','gururaj','harshad'] , columns=['osa','python','java','se'])
print("Pandas DataFrame to store the marks of students in every subject")
print("--------------------------------")
print(df)

Numpy Array
[[ 90  89  50 100]
 [ 78  90  77  89]
 [ 99  89  79  60]]

Pandas DataFrame to store the marks of students in every subject
--------------------------------
          osa  python  java   se
shridhar   90      89    50  100
gururaj    78      90    77   89
harshad    99      89    79   60


In [73]:
#Here single array stores marks of every students in one subject , it is possible when we are using dictionary method ,we can change this by using T method
import numpy as np
import pandas as pd
df = pd.DataFrame({"osa":[90,78,99,77],"python":[89,90,87,88],"java":[89,60,99,100],"se":[99,100,78,88]} ,index=["Nihal","Tanishk","Ravi","Arun"])
print(df) 

         osa  python  java   se
Nihal     90      89    89   99
Tanishk   78      90    60  100
Ravi      99      87    99   78
Arun      77      88   100   88


In [62]:
import pandas as pd
i = pd.Index(["a","b","c","d"])
#ser1 = pd.Series([1,2,3,2] ,index=i)
#ser2 = pd.Series([8,9,5,8] ,index=i)
#df = pd.DataFrame({"osa":ser1 , "java":ser2})
df = pd.DataFrame([[1,8],[2,7],[3,5],[7,4]] , index=i , columns=["osa" ,"java"])
print(df)

   osa  java
a    1     8
b    2     7
c    3     5
d    7     4


# CREATE DATAFRAME CONTAINIMG INFORMATION ABOUT CITIES

In [71]:
import numpy as np
import pandas as pd
i = pd.Index(["Karnataka","Maharastra","Gujarat"])
#pop = pd.Series([1.2,3.0,2.0] , i)
#cap = pd.Series(["Bengalure","Mumbai","Gandhinagar"] , i)
#df = pd.DataFrame({"population":pop,"capital":cap})
df = pd.Datadf = pd.DataFrame([["1.2","Bengalure"],["2.0","Mumbai"],["3.0","Gandhinagar"]] , index=["Karnataka","Maharastara","Gujarat"] , columns=["Population","Capital"])
#df = pd.DataFrame([["1.2","Bengalure"],["2.0","Mumbai"],["3.0","Gandhinagar"]] , index=["Karnataka","Maharastara","Gujarat"] , columns=["Population","Capital"]).T
print(df)
# Here 'T' is transpos of matrix which converts rows to columns and vice versa

            Population      Capital
Karnataka          1.2    Bengalure
Maharastara        2.0       Mumbai
Gujarat            3.0  Gandhinagar


Possibilities of creating DataFrame through multiple series

1. Normal Series method

2. Transpose method

3. Dictionary method (key = Hedding , values = Series)(Don't need to give name in series)
                                                      
4. 2-D array method

In [75]:
#1.NORMAL SERIES METHOD
import numpy as np
import pandas as ps
i = pd.Index(["Karnataka","Maharastra","Gujarat"])
ser1 = pd.Series([1.2,3.4,1.1] , i ,name="population")
ser2 = pd.Series(["Bengalure","Mumbai","Gandhinagar"] , i ,name="capital")
df = pd.DataFrame([ser1,ser2])
print(df)

            Karnataka Maharastra      Gujarat
population        1.2        3.4          1.1
capital     Bengalure     Mumbai  Gandhinagar


In [76]:
#2.TRANSPOSE  METHOD
import numpy as np
import pandas as ps
i = pd.Index(["Karnataka","Maharastra","Gujarat"])
ser1 = pd.Series([1.2,3.4,1.1] , i ,name="population")
ser2 = pd.Series(["Bengalure","Mumbai","Gandhinagar"] , i ,name="capital")
df = pd.DataFrame([ser1,ser2]).T
print(df)

           population      capital
Karnataka         1.2    Bengalure
Maharastra        3.4       Mumbai
Gujarat           1.1  Gandhinagar


In [89]:
#3.DICTIONARY  METHOD
import numpy as np
import pandas as ps
i = pd.Index(["Karnataka","Maharastra","Gujarat"])
ser1 = pd.Series([1.2,3.4,1.1] , i )
ser2 = pd.Series(["Bengalure","Mumbai","Gandhinagar"] , i)
df = pd.DataFrame({"population":ser1,"capital":ser2})
print(df)

            population      capital
Karnataka          1.2    Bengalure
Maharastra         3.4       Mumbai
Gujarat            1.1  Gandhinagar


In [80]:
#4.2-D METHOD
import numpy as np
import pandas as ps
#i = pd.Index(["Karnataka","Maharastra","Gujarat"])
df = pd.Datadf = pd.DataFrame([["1.2","Bengalure"],["2.0","Mumbai"],["3.0","Gandhinagar"]] , index=["Karnataka","Maharastara","Gujarat"] , columns=["Population","Capital"])
print(df)

            Population      Capital
Karnataka          1.2    Bengalure
Maharastara        2.0       Mumbai
Gujarat            3.0  Gandhinagar


# HOW TO ADD NEW DATA TO A SERIES

In [83]:
import numpy as np
import pandas as pd
pop = pd.Series([1.2,3.0,2.0] , i ,name="population")
print(pop.append(pd.Series({"TamilNadu":7.7})))

Karnataka     1.2
Maharastra    3.0
Gujarat       2.0
TamilNadu     7.7
dtype: float64


C:\Users\CS-L2-PC09\AppData\Local\Temp\ipykernel_9592\2737838292.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(pop.append(pd.Series({"TamilNadu":7.7})))


METHOD 1

In [85]:
import numpy as np
import pandas as pd
df = pd.Datadf = pd.DataFrame([["1.2","Bengalure"],["2.0","Mumbai"],["3.0","Gandhinagar"]] , index=["Karnataka","Maharastara","Gujarat"] , columns=["Population","Capital"])
print(df.append(pd.DataFrame([["5.5","chennai"],["12.5","hyderabad"]] , index=["Tamil nadu","Andrapradesh"] , columns=["Population","Capital"])))

             Population      Capital
Karnataka           1.2    Bengalure
Maharastara         2.0       Mumbai
Gujarat             3.0  Gandhinagar
Tamil nadu          5.5      chennai
Andrapradesh       12.5    hyderabad


C:\Users\CS-L2-PC09\AppData\Local\Temp\ipykernel_9592\664069513.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame([["5.5","chennai"],["12.5","hyderabad"]] , index=["Tamil nadu","Andrapradesh"] , columns=["Population","Capital"])))


METHOD 2

In [93]:
import numpy as np
import pandas as ps
i = pd.Index(["Karnataka","Maharastra","Gujarat"])
pop = pd.Series([1.2,3.4,1.1] , i )
cap = pd.Series(["Bengalure","Mumbai","Gandhinagar"] , i)
df = pd.DataFrame({"population":pop,"capital":cap})
print(df.append(pd.DataFrame({"population":pd.Series({"Tamilnadu":5.5,"Andrapradesh":7.6}),
                             "capital":pd.Series({"Tamilnadu":"channai","Andrapradesh":"hydrabad"})
                             }
                            )
               )
     )

              population      capital
Karnataka            1.2    Bengalure
Maharastra           3.4       Mumbai
Gujarat              1.1  Gandhinagar
Tamilnadu            5.5      channai
Andrapradesh         7.6     hydrabad


C:\Users\CS-L2-PC09\AppData\Local\Temp\ipykernel_9592\435301407.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame({"population":pd.Series({"Tamilnadu":5.5,"Andrapradesh":7.6}),


# CONCAT NEW COLUMN TO DATAFRAME

In [14]:
import numpy as np
import pandas as pd
i = pd.Index(["Karnataka","Maharastra","Gujarat"])
pop = pd.Series(["4.9","9.0","8.9"] , index=i ,name="population")
cap = pd.Series(["Bengalure","Mumbai","Gandhinagar"] , index=i ,name="capital")
df = pd.DataFrame({"population":pop,"capital":cap})
#print(df)
df1 = pd.concat(
               [df , pd.DataFrame({
                                 "Area":pd.Series(["2.1","3.2","5.5"],index=i),
                                 "CM" :pd.Series(["Bomai","Shinde","xyz"],index=i)
    
               })
               ] , axis=1
                )
df1.to_csv("cities_csv")
df1

population      capital Area      CM
Karnataka         4.9    Bengalure  2.1   Bomai
Maharastra        9.0       Mumbai  3.2  Shinde
Gujarat           8.9  Gandhinagar  5.5     xyz

# PANDAS SUBSETTING

In [57]:
import numpy as np
import pandas as pd
from pandas import Series , DataFrame
ser1 = Series(np.arange(5),index=["alpha","beta","gama","delta","epsilon"])
print(ser1)

alpha      0
beta       1
gama       2
delta      3
epsilon    4
dtype: int32


In [23]:
ser1[:2]

alpha    0
beta     1
dtype: int32

In [24]:
ser1[["beta","delta"]]

beta     1
delta    3
dtype: int32

In [25]:
ser1["beta":"delta"]

beta     1
gama     2
delta    3
dtype: int32

In [29]:
ser1[ser1 > 3]

elipson    4
dtype: int32

In [31]:
print(ser1 > 3)

alpha      False
beta       False
gama       False
delta      False
elipson     True
dtype: bool


In [32]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
ser2 = Series(["zero","one","two","three","four"], index=[3,2,4,0,1])
print(ser2)

3     zero
2      one
4      two
0    three
1     four
dtype: object


In [33]:
ser2[2:4]     #Ambigious , it uses defalt indexing

4      two
0    three
dtype: object

In [34]:
ser2.iloc[2:4]     #uses default indexing

4      two
0    three
dtype: object

In [35]:
ser2.loc[2:4]   #uses series indexing

2    one
4    two
dtype: object

In [37]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
df = DataFrame(np.arange(21).reshape(7,3), columns=['AAA','BBB','CCC'], index=["alpha","beta","gama","delta","epsilon","zeta","eta"])
df

AAA  BBB  CCC
alpha      0    1    2
beta       3    4    5
gama       6    7    8
delta      9   10   11
epsilon   12   13   14
zeta      15   16   17
eta       18   19   20

In [38]:
df.AAA

alpha       0
beta        3
gama        6
delta       9
epsilon    12
zeta       15
eta        18
Name: AAA, dtype: int32

In [40]:
df["AAA"]

alpha       0
beta        3
gama        6
delta       9
epsilon    12
zeta       15
eta        18
Name: AAA, dtype: int32

In [42]:
df[["BBB","CCC"]]

BBB  CCC
alpha      1    2
beta       4    5
gama       7    8
delta     10   11
epsilon   13   14
zeta      16   17
eta       19   20

In [45]:
df.iloc[1:3, 1:2]  # SYNTSX : df.iloc[ row , column ]

BBB
beta    4
gama    7

In [50]:
df.loc['beta':'delta', 'BBB':'CCC']

BBB  CCC
beta     4    5
gama     7    8
delta   10   11

In [51]:
df.iloc[:, 1:3]

BBB  CCC
alpha      1    2
beta       4    5
gama       7    8
delta     10   11
epsilon   13   14
zeta      16   17
eta       19   20

In [52]:
df.iloc[:, 1:3].loc[['alpha', 'gama', 'zeta']]

BBB  CCC
alpha    1    2
gama     7    8
zeta    16   17

In [53]:
df2 = df.iloc[:, 1:3].loc[['alpha', 'gama', 'zeta']].copy()
df2

BBB  CCC
alpha    1    2
gama     7    8
zeta    16   17

In [54]:
df2['CCC'] = Series({'alpha':11, 'gama':18, 'zeta':5})
df2

BBB  CCC
alpha    1   11
gama     7   18
zeta    16    5

In [55]:
df2.iloc[1, 1] = 2
df2

BBB  CCC
alpha    1   11
gama     7    2
zeta    16    5

In [58]:
df2.iloc[:, 1] = 0
df2

BBB  CCC
alpha    1    0
gama     7    0
zeta    16    0